branches:
  - main

name-template: 'Version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

sort-by: title
sort-direction: ascending

categories:
  - title: "## Added"
    labels:
      - 'type: feature'
    exclude-labels:
      - 'area: translations'
  - title: "## Fixed"
    labels:
      - 'type: bug'
    exclude-labels:
      - 'area: translations'
  - title: "## Improved"
    labels:
      - 'type: enhancement'
      - 'type: performance'
      - 'type: refactor'
    exclude-labels:
      - 'area: translations'
  - title: '## Translations'
    labels:
      - 'area: translations'

exclude-labels:
  - 'duplicate'
  - 'invalid'
  - 'status: wont fix'
  - 'type: chore'
  - 'type: docs'

change-template: '- $TITLE (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: enhancement'
      - 'type: performance'
  default: patch

template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
