name: 🐞 Bug Report
description: Report a problem or unexpected behavior in TrenchKit
title: "Bug - "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        Please fill out the sections below so the issue can be reproduced and fixed more easily.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: Tell us what you expected to happen vs what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open TrenchKit
        2. Install mod X
        3. Enable profile Y
        4. Crash occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: TrenchKit version
      description: Version number or commit hash (shown in About dialog)
      placeholder: "e.g. v0.1.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or error output
      description: Paste any relevant logs, error messages, or stack traces.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, mods involved, profiles used, or anything else helpful.
    validations:
      required: false
