name: Bug Report
description: Report a problem or unexpected behavior in TrenchKit
title: "Bug - "
labels: ["type: bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: Tell us what you expected to happen vs what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open TrenchKit
        2. Install mod X
        3. Enable profile Y
        4. Crash occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of TrenchKit is affected?
      options:
        - Mod install
        - Mod updates
        - Profiles
        - Backups
        - Conflicts
        - Launcher
        - Settings / UI
        - Auth (Nexus / Itch)
        - Updater (self-update)
        - Translations
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TrenchKit version
      description: Version number shown in Settings
      placeholder: "e.g. 1.1.5"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Operating system
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or error output
      description: Paste any relevant logs, error messages, or stack traces.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, mods involved, profiles used, or anything else helpful.
    validations:
      required: false
