name: Feature Request
description: Suggest an idea or improvement for TrenchKit
title: "Feature - "
labels: ["type: feature"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like TrenchKit to do?
      placeholder: "I would like TrenchKit to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of TrenchKit does this affect?
      options:
        - Mod install
        - Mod updates
        - Profiles
        - Backups
        - Conflicts
        - Launcher
        - Settings / UI
        - Auth (Nexus / Itch)
        - Updater (self-update)
        - Translations
        - Other
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to help implement this?
      options:
        - Yes, I can contribute code
        - Maybe (with guidance)
        - No, suggestion only
    validations:
      required: false
